apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress
spec:
  mariaDbRef:
    name: mariadb-wordpress
  passwordSecretKeyRef:
    name: mariadb-wordpress
    key: user-password

  maxUserConnections: 20
  host: "%"

  cleanupPolicy: Delete
  
  
  requeueInterval: 10h
  retryInterval: 30s